{{- if .Values.auth.enabled }}
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: authcartadd
  labels:
    {{- include "teastore.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.auth.service.annotations }}
    {{- toYaml . | nindent 8 }}
    {{- end }}
spec:
  template:
    spec:
      {{- with .Values.auth.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - image: "{{ .Values.auth.image.base }}/auth_cart_add:{{ .Values.auth.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.auth.image.pullPolicy }}
          resources:
            requests:
              cpu: 250m
              memory: 250Mi
            limits:
              cpu: 500m
              memory: 500Mi
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: authcartremove
  labels:
    {{- include "teastore.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.auth.service.annotations }}
    {{- toYaml . | nindent 8 }}
    {{- end }}
spec:
  template:
    spec:
      {{- with .Values.auth.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - image: "{{ .Values.auth.image.base }}/auth_cart_remove:{{ .Values.auth.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.auth.image.pullPolicy }}
          resources:
            requests:
              cpu: 500m
              memory: 250Mi
            limits:
              cpu: 1000m
              memory: 500Mi
      
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: authcartupdate
  labels:
    {{- include "teastore.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.auth.service.annotations }}
    {{- toYaml . | nindent 8 }}
    {{- end }}
spec:
  template:
    spec:
      {{- with .Values.auth.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - image: "{{ .Values.auth.image.base }}/auth_cart_update:{{ .Values.auth.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.auth.image.pullPolicy }}
          resources:
            requests:
              cpu: 500m
              memory: 250Mi
            limits:
              cpu: 1000m
              memory: 500Mi
      
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: authuserloggedin
  labels:
    {{- include "teastore.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.auth.service.annotations }}
    {{- toYaml . | nindent 8 }}
    {{- end }}
spec:
  template:
    spec:
      {{- with .Values.auth.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - image: "{{ .Values.auth.image.base }}/auth_user_loggedin:{{ .Values.auth.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.auth.image.pullPolicy }}
          resources:
            requests:
              cpu: 500m
              memory: 250Mi
            limits:
              cpu: 1000m
              memory: 500Mi
      
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: authuserlogin
  labels:
    {{- include "teastore.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.auth.service.annotations }}
    {{- toYaml . | nindent 8 }}
    {{- end }}
spec:
  template:
    spec:
      {{- with .Values.auth.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - image: "{{ .Values.auth.image.base }}/auth_user_login:{{ .Values.auth.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.auth.image.pullPolicy }}
          resources:
            requests:
              cpu: 500m
              memory: 250Mi
            limits:
              cpu: 1000m
              memory: 500Mi
      
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: authuserlogout
  labels:
    {{- include "teastore.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.auth.service.annotations }}
    {{- toYaml . | nindent 8 }}
    {{- end }}
spec:
  template:
    spec:
      {{- with .Values.auth.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - image: "{{ .Values.auth.image.base }}/auth_user_logout:{{ .Values.auth.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.auth.image.pullPolicy }}
          resources:
            requests:
              cpu: 500m
              memory: 250Mi
            limits:
              cpu: 1000m
              memory: 500Mi
      
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: authuserorder
  labels:
    {{- include "teastore.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.auth.service.annotations }}
    {{- toYaml . | nindent 8 }}
    {{- end }}
spec:
  template:
    spec:
      {{- with .Values.auth.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - image: "{{ .Values.auth.image.base }}/auth_user_order:{{ .Values.auth.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.auth.image.pullPolicy }}
          resources:
            requests:
              cpu: 500m
              memory: 250Mi
            limits:
              cpu: 1000m
              memory: 500Mi
---
{{- end }}